/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ioleinik <ioleinik@student.42wolfsburg.de> +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/05/26 13:41:37 by ioleinik          #+#    #+#             */
/*   Updated: 2021/06/17 06:19:31 by ioleinik         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>
#include "libftprintf.h"

int	main(void)
{
	int		a = -4;
	int		b = 0;
	char	c = 'a';
	int		d = 2147483647;
	int		e = -2147483648;
	int		f = 42;
	int		g = 25;
	int		h = 4200;
	int		i = 8;
	int		j = -12;
	int		k = 123456789;
	int		l = 0;
	int		m = -12345678;
	char	*n = "abcdefghijklmnop";
	char	*o = "-a";
	char	*p = "-12";
	char	*q = "0";
	char	*r = "%%";
	char	*s = "-2147483648";
	char	*t = "0x12345678";
	char	*u = "-0";
	char	*nu = NULL;
	int		x;
	int		y;
	static char     			a01;
	static unsigned char 		a02;
	static short 				a03;
	static unsigned short 		a04;
	static int 					a05;
	static unsigned int 		a06;
	static long 				a07;
	static unsigned long 		a08;
	static long long 			a09;
	static unsigned long long 	a10;
	static char 				*a11;
	static void 				*a12;

	x = 0;
	y = 0;
	x = ft_printf("test\n");
	y = printf("test\n");
	printf("%d %d\n", x, y);
	x = ft_printf("%i, %d, %d, %d, %d, %d, %i, %d, %i, %d\n", a, b, c, d, e, f, g, h, i, j);
	y = printf("%i, %d, %d, %d, %d, %d, %i, %d, %i, %d\n", a, b, c, d, e, f, g, h, i, j);
	printf("%d %d\n", x, y);
	x = ft_printf("%0i, %0d, %0d, %0d, %0d, %0d, %0d, %0d\n", m, l, k, i, j, a, b, c);
	y = printf("%0i, %0d, %0d, %0d, %0d, %0d, %0d, %0d\n", m, l, k, i, j, a, b, c);
	printf("%d %d\n", x, y);
	x = ft_printf("%8i, %8d, %8d, %8d, %8d, %8d, %8d, %8d\n", i, j, k, l, m, c, e, d);
	y = printf("%8i, %8d, %8d, %8d, %8d, %8d, %8d, %8d\n", i, j, k, l, m, c, e, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%-.i, %-.d, %-.d, %-.d, %-.d, %-.d, %-.d, %-.d\n", i, j, k, l, m, c, e, d);
	y = printf("%-.i, %-.d, %-.d, %-.d, %-.d, %-.d, %-.d, %-.d\n", i, j, k, l, m, c, e, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%-i, %-d, %-d, %-d, %-d, %-d, %-d, %-d\n", i, j, k, l, m, c, e, d);
	y = printf("%-i, %-d, %-d, %-d, %-d, %-d, %-d, %-d\n", i, j, k, l, m, c, e, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%.i, %.d, %.d, %.d, %.d, %.d, %.d, %.d\n", i, j, k, l, m, c, e, d);
	y = printf("%.i, %.d, %.d, %.d, %.d, %.d, %.d, %.d\n", i, j, k, l, m, c, e, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%1.i, %1.d, %1.d, %1.d, %1.d, %1.d, %1.d, %1.d\n", i, j, k, l, m, c, e, d);
	y = printf("%1.i, %1.d, %1.d, %1.d, %1.d, %1.d, %1.d, %1.d\n", i, j, k, l, m, c, e, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%1.0i, %1.0d, %1.0d, %1.0d, %1.0d, %1.0d, %1.0d, %1.0d\n", i, j, k, l, m, c, e, d);
	y = printf("%1.0i, %1.0d, %1.0d, %1.0d, %1.0d, %1.0d, %1.0d, %1.0d\n", i, j, k, l, m, c, e, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%*i, %*d, %*d, %*d, %*d, %*d, %*d, %*d\n", a, i, a, j, a, k, a, l, a, m, a, c, a, e, a, d);
	y = printf("%*i, %*d, %*d, %*d, %*d, %*d, %*d, %*d\n", a, i, a, j, a, k, a, l, a, m, a, c, a, e, a, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%0*i, %0*d, %0*d, %0*d\n", a, i, a, j, a, l, a, c);
	y = printf("%0*i, %0*d, %0*d, %0*d\n", a, i, a, j, a, l, a, c);
	printf("%d %d\n", x, y);
	x = ft_printf("%-*i, %-*d, %-*d, %-*d, %-*d, %-*d, %-*d, %-*d\n", a, i, a, j, a, k, a, l, a, m, a, c, a, e, a, d);
	y = printf("%-*i, %-*d, %-*d, %-*d, %-*d, %-*d, %-*d, %-*d\n", a, i, a, j, a, k, a, l, a, m, a, c, a, e, a, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%.*i, %.*d, %.*d, %.*d, %.*d, %.*d, %.*d, %.*d\n", a, i, a, j, a, k, a, l, a, m, a, c, a, e, a, d);
	y = printf("%.*i, %.*d, %.*d, %.*d, %.*d, %.*d, %.*d, %.*d\n", a, i, a, j, a, k, a, l, a, m, a, c, a, e, a, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%*s, %*s, %*s, %*s\n", a, o, a, p, a, q, a, r);
	y = printf("%*s, %*s, %*s, %*s\n", a, o, a, p, a, q, a, r);
	printf("%d %d\n", x, y);
	x = ft_printf("%-*s, %-*s, %-*s, %-*s, %-*s, %-*s, %-*s, %-*s\n", a, n, a, o, a, p, a, q, a, r, a, s, a, t, a, u);
	y = printf("%-*s, %-*s, %-*s, %-*s, %-*s, %-*s, %-*s, %-*s\n", a, n, a, o, a, p, a, q, a, r, a, s, a, t, a, u);
	printf("%d %d\n", x, y);
	x = ft_printf("%.*s, %.*s, %.*s, %.*s, %.*s, %.*s, %.*s, %.*s\n", a, n, a, o, a, p, a, q, a, r, a, s, a, t, a, u);
	y = printf("%.*s, %.*s, %.*s, %.*s, %.*s, %.*s, %.*s, %.*s\n", a, n, a, o, a, p, a, q, a, r, a, s, a, t, a, u);
	printf("%d %d\n", x, y);
	x = ft_printf("%.s, %.s, %.s, %.s, %.s\n", n, o, p, q, r);
	y = printf("%.s, %.s, %.s, %.s, %.s\n", n, o, p, q, r);
	printf("%d %d\n", x, y);
	x = ft_printf("%1.s, %1.s, %1.s, %1.s, %1.s\n", n, o, p, q, r);
	y = printf("%1.s, %1.s, %1.s, %1.s, %1.s\n", n, o, p, q, r);
	printf("%d %d\n", x, y);
	x = ft_printf("%.2s, %.2s, %.2s, %.2s, %.2s\n", n, o, p, q, r);
	y = printf("%.2s, %.2s, %.2s, %.2s, %.2s\n", n, o, p, q, r);
	printf("%d %d\n", x, y);
	x = ft_printf("%*.*s, %*.*s, %*.*s, %*.*s, %*.*s, %*.*s, %*.*s, %*.*s\n", a, b, n, a, b, o, a, b, p, a, b, q, a, b, r, a, b, s, a, b, t, a, b, u);
	y = printf("%*.*s, %*.*s, %*.*s, %*.*s, %*.*s, %*.*s, %*.*s, %*.*s\n", a, b, n, a, b, o, a, b, p, a, b, q, a, b, r, a, b, s, a, b, t, a, b, u);
	printf("%d %d\n", x, y);
	x = ft_printf("%-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s\n", a, b, n, a, b, o, a, b, p, a, b, q, a, b, r, a, b, s, a, b, t, a, b, u);
	y = printf("%-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s\n", a, b, n, a, b, o, a, b, p, a, b, q, a, b, r, a, b, s, a, b, t, a, b, u);
	printf("%d %d\n", x, y);
	x = ft_printf("%u, %x, %X, %u, %x, %X, %u, %x, %X, %u, %x, \n%X, %u, %x, %X, %u, %x, %X, %u, %x, %X, %u, %x, %X\n", i, i, i, j, j, j, k, k, k, l, l, l, m, m, m, c, c, c, d, d, d, e, e, e);
	y = printf("%u, %x, %X, %u, %x, %X, %u, %x, %X, %u, %x, \n%X, %u, %x, %X, %u, %x, %X, %u, %x, %X, %u, %x, %X\n", i, i, i, j, j, j, k, k, k, l, l, l, m, m, m, c, c, c, d, d, d, e, e, e);
	printf("%d %d\n", x, y);
	x = ft_printf("%*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	y = printf("%*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X, %*u, %*x, %*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	printf("%d %d\n", x, y);
	x = ft_printf("%0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	y = printf("%0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	printf("%d %d\n", x, y);
	x = ft_printf("%0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	y = printf("%0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	printf("%d %d\n", x, y);
	x = ft_printf("%-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	y = printf("%-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X, %-*u, %-*x, %-*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	printf("%d %d\n", x, y);
	x = ft_printf("%.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	y = printf("%.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X, %.*u, %.*x, %.*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	printf("%d %d\n", x, y);
	x = ft_printf("%*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X\n", a, b, i, a, b, i, a, b, i, a, b, j, a, b, j, a, b, j, a, b, k, a, b, k, a, b, k, a, b, l, a, b, l, a, b, l, a, b, m, a, b, m, a, b, m, a, b, c, a, b, c, a, b, c, a, b, d, a, b, d, a, b, d, a, b, e, a, b, e, a, b, e);
	y = printf("%*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X, %*.*u, %*.*x, %*.*X\n", a, b, i, a, b, i, a, b, i, a, b, j, a, b, j, a, b, j, a, b, k, a, b, k, a, b, k, a, b, l, a, b, l, a, b, l, a, b, m, a, b, m, a, b, m, a, b, c, a, b, c, a, b, c, a, b, d, a, b, d, a, b, d, a, b, e, a, b, e, a, b, e);
	printf("%d %d\n", x, y);
	x = ft_printf("%*.*u, %*.*x, %*.*X\n", a, b, e, a, b, e, a, b, e);
	y = printf("%*.*u, %*.*x, %*.*X\n", a, b, e, a, b, e, a, b, e);
	printf("%d %d\n", x, y);
	x = ft_printf("%12.12i, %12.12d\n", -42, 42);
	y = printf("%12.12i, %12.12d\n", -42, 42);
	printf("%d %d\n", x, y);
	x = ft_printf("%-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X\n", a, b, i, a, b, i, a, b, i, a, b, j, a, b, j, a, b, j, a, b, k, a, b, k, a, b, k, a, b, l, a, b, l, a, b, l, a, b, m, a, b, m, a, b, m, a, b, c, a, b, c, a, b, c, a, b, d, a, b, d, a, b, d, a, b, e, a, b, e, a, b, e);
	y = printf("%-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X, %-*.*u, %-*.*x, %-*.*X\n", a, b, i, a, b, i, a, b, i, a, b, j, a, b, j, a, b, j, a, b, k, a, b, k, a, b, k, a, b, l, a, b, l, a, b, l, a, b, m, a, b, m, a, b, m, a, b, c, a, b, c, a, b, c, a, b, d, a, b, d, a, b, d, a, b, e, a, b, e, a, b, e);
	printf("%d %d\n", x, y);
	x = ft_printf("%p, %x, %p, %x, %p, %x, %p, %x\n", (void *)209590960, 209590960, (void *)207038912, 207038912, (void *)1, 1, NULL, 0);
	y = printf("%p, %x, %p, %x, %p, %x, %p, %x\n", (void *)209590960, 209590960, (void *)207038912, 207038912, (void *)1, 1, NULL, 0);
	printf("%d %d\n", x, y);
	x = ft_printf("%*p, %*x, %*p, %*x, %*p, %*x, %*p, %*x|\n", a, (void *)209590960, a, 209590960, a, (void *)207038912, a, 207038912, a, (void *)1, a, 1, a, NULL, a, 0);
	y = printf("%*p, %*x, %*p, %*x, %*p, %*x, %*p, %*x|\n", a, (void *)209590960, a, 209590960, a, (void *)207038912, a, 207038912, a, (void *)1, a, 1, a, NULL, a, 0);
	printf("%d %d\n", x, y);
	x = ft_printf("%-*p, %-*x, %-*p, %-*x, %-*p, %-*x, %-*p, %-*x\n", a, (void *)209590960, a, 209590960, a, (void *)207038912, a, 207038912, a, (void *)1, a, 1, a, NULL, a, 0);
	y = printf("%-*p, %-*x, %-*p, %-*x, %-*p, %-*x, %-*p, %-*x\n", a, (void *)209590960, a, 209590960, a, (void *)207038912, a, 207038912, a, (void *)1, a, 1, a, NULL, a, 0);
	printf("%d %d\n", x, y);
	x = ft_printf("%-*.*i, %-*.*d, %-*.*d, %-*.*d, %-*.*d, %-*.*d\n", a, b, i, a, b, j, a, b, k, a, b, l, a, b, m, a, b, c);
	y = printf("%-*.*i, %-*.*d, %-*.*d, %-*.*d, %-*.*d, %-*.*d\n", a, b, i, a, b, j, a, b, k, a, b, l, a, b, m, a, b, c);
	printf("%d %d\n", x, y);
	x = ft_printf("%-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s\n", a, b, n, a, b, o, a, b, p, a, b, q, a, b, r, a, b, s, a, b, t, a, b, u);
	y = printf("%-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s, %-*.*s\n", a, b, n, a, b, o, a, b, p, a, b, q, a, b, r, a, b, s, a, b, t, a, b, u);
	printf("%d %d\n", x, y);
	x = ft_printf("%-*p, %-*x, %-*p, %-*x, %-*p, %-*x, %-*p, %-*x\n", a, (void *)209590960, a, 209590960, a, (void *)207038912, a, 207038912, a, (void *)1, a, 1, a, NULL, a, 0);
	y = printf("%-*p, %-*x, %-*p, %-*x, %-*p, %-*x, %-*p, %-*x\n", a, (void *)209590960, a, 209590960, a, (void *)207038912, a, 207038912, a, (void *)1, a, 1, a, NULL, a, 0);
	printf("%d %d\n", x, y);
	x = ft_printf("%c,  %-c, %1c, %*c,  %-*c,  %*c, %-*c\n", c, n[0], o[0], a, p[0], a, q[0], a, r[0], a, c);
	y = printf("%c,  %-c, %1c, %*c,  %-*c,  %*c, %-*c\n", c, n[0], o[0], a, p[0], a, q[0], a, r[0], a, c);
	printf("%d %d\n", x, y);
	x = ft_printf("%c,  %-c, %1c, %*c,  %-*c,  %*c, %-*c\n", c, n[0], o[0], -a, p[0], -a, q[0], -a, r[0], -a, c);
	y = printf("%c,  %-c, %1c, %*c,  %-*c,  %*c, %-*c\n", c, n[0], o[0], -a, p[0], -a, q[0], -a, r[0], -a, c);
	printf("%d %d\n", x, y);
	x = ft_printf("%c,  %-c, %1c, %*c,  %-*c,  %*c, %-*c\n", c, n[0], q[0], a, q[0], a, p[0], a, p[0], a, c);
	y = printf("%c,  %-c, %1c, %*c,  %-*c,  %*c, %-*c\n", c, n[0], q[0], a, q[0], a, p[0], a, p[0], a, c);
	printf("%d %d\n", x, y);
	x = ft_printf("%c,  %-c, %1c, %*c,  %-*c,  %*c\n", -12, -1, -255, a, -12, a, -1, a, -255);
	y = printf("%c,  %-c, %1c, %*c,  %-*c,  %*c\n", -12, -1, -255, a, -12, a, -1, a, -255);
	printf("%d %d\n", x, y);
	x = ft_printf("%%, \t, \\, \", \', +\n");
	y = printf("%%, \t, \\, \", \', +\n");
	printf("%d %d\n", x, y);
	x = ft_printf("%%%dbada%s%%**%s**-d%%0*d%-12s0*@\n", h, "bada", r, p);
	y = printf("%%%dbada%s%%**%s**-d%%0*d%-12s0*@\n", h, "bada", r, p);
	printf("%d %d\n", x, y);
	x = ft_printf("%%%dbada%s%%**%s**-d%%0*d%-12s0*@\n", h, "bada", r, p);
	y = printf("%%%dbada%s%%**%s**-d%%0*d%-12s0*@\n", h, "bada", r, p);
	printf("%d %d\n", x, y);
	x = ft_printf("%i, %d, %d, %d, %d, %d, %u, %x, %X\n", 0, 0, 0, 0, 0, 0, 0, 0, 0);
	y = printf("%i, %d, %d, %d, %d, %d, %u, %x, %X\n", 0, 0, 0, 0, 0, 0, 0, 0, 0);
	printf("%d %d\n", x, y);
	x = ft_printf("%*i, %*d, %*d, %*d, %*d, %*d, %*u, %*x, %*X\n", a, 0, a, 0, a, 0, a, 0, a, 0, a, 0, a, 0, a, 0, a, 0);
	y = printf("%*i, %*d, %*d, %*d, %*d, %*d, %*u, %*x, %*X\n", a, 0, a, 0, a, 0, a, 0, a, 0, a, 0, a, 0, a, 0, a, 0);
	printf("%d %d\n", x, y);
	x = ft_printf("%c, %-c, %12c, %-3c, %-1c, %1c, %-2c, %-4c, %5c, %3c, %-*c, %-*c, %*c, %*c\n", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0);
	y = printf("%c, %-c, %12c, %-3c, %-1c, %1c, %-2c, %-4c, %5c, %3c, %-*c, %-*c, %*c, %*c\n", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0);
	printf("%d %d\n", x, y);
	x = ft_printf("%p %p %p %p\n", n, o, p, q);
	y = printf("%p %p %p %p\n", n, o, p, q);
	printf("%d %d\n", x, y);
	x = ft_printf("%p %p %p %p\n", r, s, t, u);
	y = printf("%p %p %p %p\n", r, s, t, u);
	printf("%d %d\n", x, y);
	x = ft_printf("%0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	y = printf("%0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X, %0*u, %0*x, %0*X\n", a, i, a, i, a, i, a, j, a, j, a, j, a, k, a, k, a, k, a, l, a, l, a, l, a, m, a, m, a, m, a, c, a, c, a, c, a, d, a, d, a, d, a, e, a, e, a, e);
	printf("%d %d\n", x, y);
	x = ft_printf("%*.*i, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d\n", a, b, i, a, b, j, a, b, k, a, b, l, a, b, m, a, b, c, a, b, e, a, b, d);
	y = printf("%*.*i, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d\n", a, b, i, a, b, j, a, b, k, a, b, l, a, b, m, a, b, c, a, b, e, a, b, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%-*.*i, %-*.*d, %-*.*d, %-*.*d, %-*.*d, %-*.*d, %-*.*d, %-*.*d\n", a, b, i, a, b, j, a, b, k, a, b, l, a, b, m, a, b, c, a, b, e, a, b, d);
	y = printf("%-*.*i, %-*.*d, %-*.*d, %-*.*d, %-*.*d, %-*.*d, %-*.*d, %-*.*d\n", a, b, i, a, b, j, a, b, k, a, b, l, a, b, m, a, b, c, a, b, e, a, b, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%*.*i, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d\n", a, b, -42, a, b, 42, -a, -b, -42, -a, -b, 42, -a, b, -42, -a, b, 42, a, -b, -42, a, -b, 42);
	y = printf("%*.*i, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d, %*.*d\n", a, b, -42, a, b, 42, -a, -b, -42, -a, -b, 42, -a, b, -42, -a, b, 42, a, -b, -42, a, -b, 42);
	printf("%d %d\n", x, y);
	x = ft_printf("%1s, %1s, %1s, %1s, %1s\n", n, o, p, q, r);
	y = printf("%1s, %1s, %1s, %1s, %1s\n", n, o, p, q, r);
	printf("%d %d\n", x, y);
	x = ft_printf("%4s, %4s, %4s, %4s, %4s\n", n, o, p, q, r);
	y = printf("%4s, %4s, %4s, %4s, %4s\n", n, o, p, q, r);
	printf("%d %d\n", x, y);
	x = ft_printf("%15s, %15s, %15s, %15s, %15s\n", n, o, p, q, r);
	y = printf("%15s, %15s, %15s, %15s, %15s\n", n, o, p, q, r);
	printf("%d %d\n", x, y);
	x = ft_printf("%7.5s\n", "bombastic");
	y = printf("%7.5s\n", "bombastic");
	printf("%d %d\n", x, y);
	x = ft_printf("%-7.5s\n", "tubular");
	y = printf("%-7.5s\n", "tubular");
	printf("%d %d\n", x, y);
	x = ft_printf("%7.3s%7.7s\n", "hello", "world");
	y = printf("%7.3s%7.7s\n", "hello", "world");
	printf("%d %d\n", x, y);
	x = ft_printf("%7.3s%3.7s\n", "hello", "world");
	y = printf("%7.3s%3.7s\n", "hello", "world");
	printf("%d %d\n", x, y);
	x = ft_printf("%7.7s%7.3s\n", "hello", "world");
	y = printf("%7.7s%7.3s\n", "hello", "world");
	printf("%d %d\n", x, y);
	x = ft_printf("%3.7s%7.3s\n", "hello", "world");
	y = printf("%3.7s%7.3s\n", "hello", "world");
	printf("%d %d\n", x, y);
	x = ft_printf("%7.3s%7.3s\n", "hello", "world");
	y = printf("%7.3s%7.3s\n", "hello", "world");
	printf("%d %d\n", x, y);
	x = ft_printf("%3.3s%7.3s\n", "hello", "world");
	y = printf("%3.3s%7.3s\n", "hello", "world");
	printf("%d %d\n", x, y);
	x = ft_printf("%7.3s%3.3s\n", "hello", "world");
	y = printf("%7.3s%3.3s\n", "hello", "world");
	printf("%d %d\n", x, y);
	x = ft_printf("%.5s|%7s|\n", "yo", "boi");
	y = printf("%.5s|%7s|\n", "yo", "boi");
	printf("%d %d\n", x, y);
	x = ft_printf("%7.5s\n", "yolo");
	y = printf("%7.5s\n", "yolo");
	printf("%d %d\n", x, y);
	x = ft_printf("%8.5i\n", 34);
	y = printf("%8.5i\n", 34);
	printf("%d %d\n", x, y);
	x = ft_printf("%10.5i\n", -216);
	y = printf("%10.5i\n", -216);
	printf("%d %d\n", x, y);
	x = ft_printf("%8.3i\n", 8375);
	y = printf("%8.3i\n", 8375);
	printf("%d %d\n", x, y);
	x = ft_printf("%8.3i\n", -8375);
	y = printf("%8.3i\n", -8375);
	printf("%d %d\n", x, y);
	x = ft_printf("%.4i\n", -2372);
	y = printf("%.4i\n", -2372);
	printf("%d %d\n", x, y);
	x = ft_printf("%08.5i\n", 34);
	y = printf("%08.5i\n", 34);
	printf("%d %d\n", x, y);
	x = ft_printf("%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p\n",&a01,&a02,&a03,&a04,&a05,&a06,&a07,&a08,&a09,&a10,&a11,&a12);
	y = printf("%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p%16p\n",&a01,&a02,&a03,&a04,&a05,&a06,&a07,&a08,&a09,&a10,&a11,&a12);
	printf("%d %d\n", x, y);
	x = ft_printf("%.5d\n", -2372);
	y = printf("%.5d\n", -2372);
	printf("%d %d\n", x, y);
	x = ft_printf("{%05.*d}\n", -15, 42);
	y = printf("{%05.*d}\n", -15, 42);
	printf("%d %d\n", x, y);
	x = ft_printf("%.1i, %.1d, %.1d, %.1d, %.1d, %.1d, %.1d, %.1d\n", i, j, k, l, m, c, e, d);
	y = printf("%.1i, %.1d, %.1d, %.1d, %.1d, %.1d, %.1d, %.1d\n", i, j, k, l, m, c, e, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%1.1i, %1.1d, %1.1d, %1.1d, %1.1d, %1.1d, %1.1d, %1.1d\n", i, j, k, l, m, c, e, d);
	y = printf("%1.1i, %1.1d, %1.1d, %1.1d, %1.1d, %1.1d, %1.1d, %1.1d\n", i, j, k, l, m, c, e, d);
	printf("%d %d\n", x, y);
	x = ft_printf("%20.5d\n", -1024);
	y = printf("%20.5d\n", -1024);
	printf("%d %d\n", x, y);
	x = ft_printf("%8.3i\n", -8473);
	y = printf("%8.3i\n", -8473);
	printf("%d %d\n", x, y);
	x = ft_printf("%p\n", NULL);
	y = printf("%p\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%15p\n", NULL);
	y = printf("%15p\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%16.*s\n", -64, "test");
	y = printf("%16.*s\n", -64, "test");
	printf("%d %d\n", x, y);
	x = ft_printf("%0*.*d\n", 1, 0, 0);
	y = printf("%0*.*d\n", 1, 0, 0);
	printf("%d %d\n", x, y);
	x = ft_printf("%0*d\n", 1, 0);
	y = printf("%0*d\n", 1, 0);
	printf("%d %d\n", x, y);
	x = ft_printf("%0*.*d|%0*.*d|\n", 2, 0, 8, 2, 0, 0);
	y = printf("%0*.*d|%0*.*d|\n", 2, 0, 8, 2, 0, 0);
	printf("%d %d\n", x, y);
	x = ft_printf("%0*.*d\n", 4, 0, -12);
	y = printf("%0*.*d\n", 4, 0, -12);
	printf("%d %d\n", x, y);
	x = ft_printf("%s\n", NULL);
	y = printf("%s\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%.03s\n", NULL);
	y = printf("%.03s\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%.*s, %.0s, %.1s, %.2s, %.4s, %.8s\n", -2, NULL, NULL, NULL, NULL, NULL, NULL);
	y = printf("%.*s, %.0s, %.1s, %.2s, %.4s, %.8s\n", -2, NULL, NULL, NULL, NULL, NULL, NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%*.*s|\n", -2, 3, "abcdef");
	y = printf("%*.*s|\n", -2, 3, "abcdef");
	printf("%d %d\n", x, y);
	x = ft_printf("%-2.4s|\n", NULL);
	y = printf("%-2.4s|\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%.03s|\n", NULL);
	y = printf("%.03s|\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%.4s|\n", NULL);
	y = printf("%.4s|\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%.2s|\n", NULL);
	y = printf("%.2s|\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%.s|\n", NULL);
	y = printf("%.s|\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%-4s|\n", NULL);
	y = printf("%-4s|\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%.03s|\n", NULL);
	y = printf("%.03s|\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%-8.12s|\n", NULL);
	y = printf("%-8.12s|\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%8s|\n", NULL);
	y = printf("%8s|\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%8s|\n", NULL);
	y = printf("%8s|\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf(nu, NULL);
	y = printf(nu, NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("%x\n", -1);
	y = printf("%x\n", -1);
	printf("%d %d\n", x, y);
	x = ft_printf("Hello 42 school! %s\n", NULL);
	y = printf("Hello 42 school! %s\n", NULL);
	printf("%d %d\n", x, y);
	x = ft_printf("[% %]\n");
	y = printf("[% %]\n");
	printf("%d %d\n", x, y);
	x = ft_printf("[%  %]\n");
	y = printf("[%  %]\n");
	printf("%d %d\n", x, y);
	x = ft_printf("[%   %]\n");
	y = printf("[%   %]\n");
	printf("%d %d\n", x, y);
	x = ft_printf("[%%]\n");
	y = printf("[%%]\n");
	printf("%d %d\n", x, y);
	x = ft_printf("%10.5s\n", "Hello 42 Student");
	y = printf("%10.5s\n", "Hello 42 Student");
	printf("%d %d\n", x, y);
	x = ft_printf("");
	y = printf("");
	printf("%d %d\n", x, y);
	x = ft_printf("%%---%---.0dbada%.0s%%*-*%s**-.d%%0*d%-12.s0*@\n", h, "bada", r, p);
	y = printf("%%---%---.0dbada%.0s%%*-*%s**-.d%%0*d%-12.s0*@\n", h, "bada", r, p);
	printf("%d %d\n", x, y);
	return (0);
}
